version: '3'

services:
  nextjs-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        DOT_ENV_PRODUCTION_FILE: .env.production
    image: nextjs-app-production
    ports:
      - '3100:3000'
    environment:
      - DATABASE_URL=postgresql://testpg:testpg@132.145.183.252:49169/testpg?schema=public
